Latest update

diff --git a/test.yaml b/test.yaml
--- a/test.yaml
+++ b/test.yaml
@@ -62,7 +62,7 @@ steps:
 
         # Exit with error if digest not found in the ACR
         if [ -z "${image_tag}" ]; then
-            echo "Image tag not found for Digest: "${REPOSITORY}"@""${DIGEST}" >&2
+            echo "Error: image tag not found for Digest: "${REPOSITORY}"@""${DIGEST}" >&2
             exit 1
         fi
 
